# The user account that Nginx uses to run.
user  nginx;
# 'auto' tells Nginx to use all available CPU cores to handle traffic.
worker_processes  auto;

# Where to save error messages and how serious they should be ('warn' level).
error_log  /var/log/nginx/error.log warn;
# A file that stores the Process ID of the running Nginx service.
pid        /var/run/nginx.pid;

events {
    # The maximum number of people that can connect at the exact same time.
    worker_connections 1024;
}

http {
    # Helps Nginx understand different file types (like images vs. text).
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # --- JSON log format ---
    # This is CRITICAL for your Python code. It tells Nginx to write logs in 
    # a "Key: Value" format (JSON) so the 'json.loads()' in your monitor can read it.
    log_format json escape=json
      '{ "time_local": "$time_local", '
      '"remote_addr": "$remote_addr", '        # The visitor's IP address.
      '"request_method": "$request_method", '  # Was it a GET or POST?
      '"request": "$request", '                # The specific URL they visited.
      '"status": "$status", '                  # The result code (e.g., 200 for OK, 404 for Not Found).
      '"body_bytes_sent": "$body_bytes_sent", '# How much data was sent to the user.
      '"http_referer": "$http_referer", '      # The website they came from.
      '"http_user_agent": "$http_user_agent" }'; # The browser/device they used.

    # Tells Nginx to use the 'json' format we just created and save it to this specific file.
    # Your Python 'Monitor' module watches this exact file path.
    access_log /var/log/nginx/hng-access.log json;

    # Speed optimizations for sending files and keeping connections open.
    sendfile        on;
    keepalive_timeout  65;

    # --- Upstream ---
    # This defines the "Back-end" server (your Nextcloud container) where the actual website lives.
    upstream nextcloud {
        server nextcloud:80;
    }

    # --- Server Block ---
    # This is the virtual host configuration.
    server {
        listen 80;               # Listen for web traffic on Port 80 (standard HTTP).
        server_name localhost;    # The domain name this server responds to.

        # The "Location /" block handles everything that comes to the root of the site.
        location / {
            # Take the incoming request and hand it over to the 'nextcloud' upstream defined above.
            proxy_pass http://nextcloud;
            
            # These 'header' lines make sure the back-end (Nextcloud) knows the 
            # REAL IP of the visitor, instead of just seeing Nginx's IP.
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}